<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends EntityRepository
{
    public function findByDate($quantity){
        
        $count = $this->createQueryBuilder();

        $count->select('quantity', $quantity)
             ->andWhere('visit', $visit);             

            return $count
            ->getQuery()
            ->getResult();
    }
}